### ISSUE TITLE
labels key issue

### ISSUE THREAD

**Issue by dkarty** [WannaGetDSJobInSanFrancisco/Machine_Notebooks#1]
Hi @HireTheHero !
I saw the issue you mentioned here https://github.com/facebookresearch/vilbert-multi-task/issues/90
I have the same issue...

and I saw your comment at the end of the notebook: 
https://github.com/HireTheHero/Machine_Notebooks/blob/main/ViLBERT.ipynb
saying: 

> one issue remaining, however it seems is raised from another repository, therefore just ignore it for now and proceed

How did you manage to ignore it and proceed? were you able to get the prediction on the demo image?

Thanks a lot!

**Comment by HireTheHero** [comment]
Hi @dkarty 
At that moment, I was seeking for the way of reproducing vilbert result in [hateful memes challenge](https://github.com/drivendataorg/hateful-memes).
The error mentioned in the aforementioned issue is caused by [masked-rcnn repo](https://github.com/facebookresearch/maskrcnn-benchmark/issues/947) for feature extraction, which I thought I could find a workaround (so I wrote `just ignore it`).
As you may know, their vilbert repo is archived (with many issues, I would say) and the model is incorporated into [mmf](https://mmf.sh/) framework - which works good for my purpose as of now.
Not sure about your usage of vilbert repo, but hope it helps for you.

**Comment by dkarty** [comment]
I see, thank you! 
I'll try to use vilbert from mmf
